import Config

# LiveDeps: prod points at the real context modules.
config :foyer,
  accounts_context: Foyer.Accounts,
  shifts_context: Foyer.Shifts,
  channels_context: Foyer.Channels,
  house_context: Foyer.House,
  recognitions_context: Foyer.Recognitions,
  chat_context: Foyer.Chat,
  profile_context: Foyer.Profile,
  today_context: Foyer.Today,
  # F.Profile.25 — property code from application config. All v1 users share
  # one property. A per-user property code is a v2 concern.
  property_code: "LDN·MAY"

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :foyer, FoyerWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :foyer, FoyerWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
